# Stage 1: Build Angular application
FROM node:18 AS builder
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install -g @angular/cli@latest
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port the app runs on
EXPOSE 4200

# Run ng serve
CMD ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]
