version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"

  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"