# Use the official Node.js image as base
FROM node:18 AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY backend .

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run the backend server
CMD ["node", "server.js"]
